In [2]:
import pandas as pd

data = {
    "Student" : ["A","B","C","D","E","F","G","H","I","J"],
    "Cricket" : ["Yes","Yes","Yes","No","No","Yes","No","Yes","No","Yes"],
    "Passed" : ["Yes","Yes","No","Yes","No","Yes","No","Yes","Yes","No"]
}
df = pd.DataFrame(data)
df

  Student Cricket Passed
0       A     Yes    Yes
1       B     Yes    Yes
2       C     Yes     No
3       D      No    Yes
4       E      No     No
5       F     Yes    Yes
6       G      No     No
7       H     Yes    Yes
8       I      No    Yes
9       J     Yes     No

### Students who played cricket?

In [3]:
total = len(df)

In [4]:
play_cricket = len(df[df['Cricket']=='Yes'])/total
play_cricket

0.6

### Students who passed?

In [5]:
passed = len(df[df['Passed']=='Yes'])/total
passed

0.6

### Cricket and passed

In [6]:
cricket_passed = len(df[(df['Cricket']=='Yes') & (df['Passed']=='Yes')])/total
cricket_passed

0.4

### Cricket or passed

In [7]:
cricket_or_passed = len(df[(df['Cricket']=='Yes') | (df['Passed']=='Yes')])/total
cricket_or_passed

0.8

### Probability of passed given he plays cricket

In [8]:
passed_given_cricket = cricket_passed/play_cricket                 # P(P/C) = P(PnC)/P(C)

In [9]:
passed_given_cricket

0.6666666666666667

### Bayes Theorem - probability of cricket given passed

In [10]:
cricket_given_passed = passed_given_cricket*play_cricket/passed                   # P(C/P) = P(P/C).P(C)/P(P)
cricket_given_passed

0.6666666666666667

In [11]:
data = {
    "Student" : ["A","B","C","D","E"],
    "Study_hours" : [2,4,6,8,10]
}
df = pd.DataFrame(data)
df

  Student  Study_hours
0       A            2
1       B            4
2       C            6
3       D            8
4       E           10

In [12]:
# we dont have a direct formula to calculate mean absolute deviation sowe do it step by step wiyh formula.
# xi-meu/n

In [13]:
mean_value = df['Study_hours'].mean()            # calculted mean (meu)
mean_value

np.float64(6.0)

In [14]:
df['Deviation'] = df['Study_hours']- mean_value            # xi-meu

In [15]:
df

  Student  Study_hours  Deviation
0       A            2       -4.0
1       B            4       -2.0
2       C            6        0.0
3       D            8        2.0
4       E           10        4.0

In [16]:
df['Absolute_Deviation'] = abs(df['Deviation'])           # calculated absolute deviation
df

  Student  Study_hours  Deviation  Absolute_Deviation
0       A            2       -4.0                 4.0
1       B            4       -2.0                 2.0
2       C            6        0.0                 0.0
3       D            8        2.0                 2.0
4       E           10        4.0                 4.0

In [17]:
mean_absolute_deviation = df['Absolute_Deviation'].mean()
mean_absolute_deviation

np.float64(2.4)

In [18]:
data = {
    "Student" : ["A","B","C","D","E","F","G","H"],
    "Study_hours" : [2,4,6,8,10,3,5,7],
    "Marks" : [45,55,65,80,92,50,60,72]
}
df = pd.DataFrame(data)
df

  Student  Study_hours  Marks
0       A            2     45
1       B            4     55
2       C            6     65
3       D            8     80
4       E           10     92
5       F            3     50
6       G            5     60
7       H            7     72

In [19]:
mean_value = df['Marks'].mean()
mean_value

np.float64(64.875)

In [20]:
df['Deviation'] = df['Marks'] - mean_value

In [21]:
df['Absolute_deviation'] = abs(df['Deviation'])

In [22]:
mean_absolute_deviation = df['Absolute_deviation'].mean()
mean_absolute_deviation

np.float64(12.375)

In [23]:
data = {
    "Employee" : ["E1","E2","E3","E4","E5","E6","E7"],
    "Working_Hours" : [6,8,7,9,5,10,8],
    "Salary" : [25000,32000,30000,40000,22000,45000,35000]
}
df = pd.DataFrame(data)
df

  Employee  Working_Hours  Salary
0       E1              6   25000
1       E2              8   32000
2       E3              7   30000
3       E4              9   40000
4       E5              5   22000
5       E6             10   45000
6       E7              8   35000

In [28]:
mean_value = df['Working_Hours'].mean()
df['deviation'] = df['Working_Hours']- mean_value
df['abs_deviation'] = abs(df['deviation'])
mean_abs_deviation = df['abs_deviation'].mean()
mean_abs_deviation

np.float64(1.346938775510204)