In [6]:
import pandas as pd

data = {
    "Student" : ["A","B","C","D","E","F","G","H","I","J"],
    "Passed" : ["Yes","No","Yes","Yes","No",
                "Yes","Yes","No","Yes","Yes"]
}
df = pd.DataFrame(data)
df

  Student Passed
0       A    Yes
1       B     No
2       C    Yes
3       D    Yes
4       E     No
5       F    Yes
6       G    Yes
7       H     No
8       I    Yes
9       J    Yes

In [14]:
total = len(df)
total

10

In [15]:
passed = len(df[df['Passed']=='Yes'])

In [16]:
probability = passed/total
print(probability)

0.7

In [18]:
failed = len(df[df['Passed']=='No'])

In [20]:
prob_failed = failed/total
print(prob_failed)

0.3

In [22]:
data = {
    "Student" : ["A","B","C","D","E","F"],
    "Gender" : ["Boy","Boy","Boy","Girl","Girl","Girl"],
    "Passed" : ["Yes","No","Yes","Yes","No","Yes"]
}
df = pd.DataFrame(data)
df

  Student Gender Passed
0       A    Boy    Yes
1       B    Boy     No
2       C    Boy    Yes
3       D   Girl    Yes
4       E   Girl     No
5       F   Girl    Yes

### Probability of boys or passed

In [28]:
total= len(df)

In [33]:
len(df[(df['Gender']=='Boy') | (df['Passed']=='Yes')])/total

0.8333333333333334

### Probability of girls or passed

In [34]:
len(df[(df['Gender']=='Girl') | (df['Passed']=='Yes')])/total

0.8333333333333334

### Probability of girls and passed

In [38]:
len(df[(df['Gender']=='Girl') & (df['Passed']=='No')])/total

0.16666666666666666

### Probability of boy or passed

In [40]:
len(df[(df['Gender']=='Boy') & (df['Passed']=='Yes')])/total

0.3333333333333333

In [42]:
data = {
    "Day" : [1,2,3,4,5,6,7,8,9,10],
    "Weather" : ["Hot","Hot","Hot","Cold","Cold","Hot","Cold","Hot","Cold","Hot",],
    "Brought_Ice_cream" : ["Yes","Yes","No","No","No","Yes","Yes","Yes","No","Yes",]
}
df = pd.DataFrame(data)
df

   Day Weather Brought_Ice_cream
0    1     Hot               Yes
1    2     Hot               Yes
2    3     Hot                No
3    4    Cold                No
4    5    Cold                No
5    6     Hot               Yes
6    7    Cold               Yes
7    8     Hot               Yes
8    9    Cold                No
9   10     Hot               Yes

### Hot and Brought Ice cream

In [44]:
total = len(df)

In [46]:
len(df[(df['Weather']=='Hot') & (df['Brought_Ice_cream']=='Yes')])/total

0.5

### Cold and Brought Ice cream

In [47]:
len(df[(df['Weather']=='Cold') & (df['Brought_Ice_cream']=='Yes')])/total

0.1

### Hot or Brought Ice cream

In [48]:
len(df[(df['Weather']=='Hot') | (df['Brought_Ice_cream']=='Yes')])/total

0.7

### Cold or Brought Ice cream

In [49]:
len(df[(df['Weather']=='Cold') | (df['Brought_Ice_cream']=='Yes')])/total

0.9